
# docker compose up --build

services:

  # ----- NATS Bridge -----

  nats-bridge:
    build: .
    restart: always
    # depends_on:
    #   backbone-nats:
    #     condition: service_started
    #   operational-nats:
    #     condition: service_started
    network_mode: host
    # ipc: host
    privileged: true
    environment:
      - DEVICE_ID=fieldAI
      - NATS_SERVER_URL=nats://192.168.128.132:4223
      - TELEMETRY_RATE=3.0
      # - ROS_MASTER_URI=http://hal:11311
    # volumes:
      # - ./temp:/ros1_ws/src/temp
    command: ["bash", "-c", "source devel/setup.bash && roslaunch nats_bridge nats_bridge.launch"]

  # ----- NATS and FMO Services -----

  # backbone-nats:
  #   network_mode: host
  #   restart: always
  #   image: ghcr.io/tiiuae/tii-backbone-nats-server:firefighter-caltech-demo
  #   environment:
  #     DEVICE_ID: fieldAI
  #     MDNS_SERVER_ENABLED: false
  #     NATS_SERVER_URL: nats://192.168.128.132:4222
  #   volumes:
  #     - backbone-nats-storage:/tmp/nats

  # operational-nats:
  #   network_mode: host
  #   restart: always
  #   image: ghcr.io/tiiuae/tii-operational-nats-server:firefighter-caltech-demo
  #   environment:
  #     DEVICE_ID: fieldAI
  #     NATS_SERVER_URL: nats://192.168.128.132:4223
  #   volumes:
  #     - operational-nats-storage:/tmp/nats

  # swarm-agent:
  #   depends_on:
  #     backbone-nats:
  #       condition: service_started
  #     operational-nats:
  #       condition: service_started
  #   network_mode: host
  #   restart: always
  #   image: ghcr.io/tiiuae/tii-swarm-agent:3.0.0
  #   environment:
  #     DEVICE_ID: fieldAI
  #     DEVICE_TYPE: rover
  #     DEVICE_ALIAS: fieldAI
  #     BACKBONE_URL: nats://192.168.128.132:4222
  #     OPERATIONAL_URL: nats://192.168.128.132:4223
  #     NATS_SERVER_URL: nats://192.168.128.132:4223
  #     NATS_TLS: unavailable
  #     DEVICE_IP: 192.168.128.132
  #     MDSN_IP_ADDRESS: 192.168.128.132
  #   volumes:
  #     - ./gazebo-sandbox/compose-files/mount/sitl_certs:/certs

# volumes:
#   backbone-nats-storage:
#   operational-nats-storage: