
# HOSTNAME=$(hostname) docker compose up --build -d

services:

  # ----- NATS Bridge -----

  nats-bridge:
    build: .
    restart: always
    # depends_on:
    #   backbone-nats:
    #     condition: service_started
    #   operational-nats:
    #     condition: service_started
    network_mode: host
    # ipc: host
    privileged: true
    environment:
      - DEVICE_ID=fieldAI
      - NATS_SERVER_URL=nats://192.168.128.132:4223
      - TELEMETRY_RATE=3.0
      # - ROS_MASTER_URI=http://hal:11311
    # volumes:
      # - ./temp:/ros1_ws/src/temp
    command: ["bash", "-c", "source devel/setup.bash && roslaunch nats_bridge nats_bridge.launch"]
