
# docker compose up --build -d

services:

  # ----- NATS Bridge -----

  nats-bridge:
    build: .
    restart: always
    network_mode: host
    privileged: true
    environment:
      - DEVICE_ID=fieldAI
      # - ROS_MASTER_URI=http://hal:11311
    command: ["bash", "-c", "source devel/setup.bash && roslaunch webrtc_launch webrtc.launch"]
